// Additional vocabulary - English Trainer v2
const EXTRA_WORDS = [
{w:'accept',p:'v.',c:'接受',s:'Please accept my apology.',cat:'work'},
{w:'account',p:'n.',c:'账户',s:'I opened a bank account.',cat:'work'},
{w:'achieve',p:'v.',c:'实现/达到',s:'She achieved her goal.',cat:'work'},
{w:'adapt',p:'v.',c:'适应',s:'You must adapt to changes.',cat:'work'},
{w:'advantage',p:'n.',c:'优势',s:'What is the advantage?',cat:'work'},
{w:'ambition',p:'n.',c:'野心/抱负',s:'He has great ambition.',cat:'work'},
{w:'analyze',p:'v.',c:'分析',s:'Analyze the data carefully.',cat:'work'},
{w:'apply',p:'v.',c:'申请',s:'Apply for the job online.',cat:'work'},
{w:'approach',p:'v./n.',c:'接近/方法',s:'A new approach is needed.',cat:'work'},
{w:'assign',p:'v.',c:'分配',s:'The teacher assigned homework.',cat:'work'},
{w:'assist',p:'v.',c:'协助',s:'Can you assist me?',cat:'work'},
{w:'assume',p:'v.',c:'假设',s:'Don\'t assume anything.',cat:'work'},
{w:'attend',p:'v.',c:'出席',s:'Please attend the meeting.',cat:'work'},
{w:'authority',p:'n.',c:'权威',s:'Who is in authority here?',cat:'work'},
{w:'available',p:'adj.',c:'可用的',s:'Is this room available?',cat:'work'},
{w:'average',p:'adj./n.',c:'平均的',s:'The average score is 80.',cat:'work'},
{w:'balance',p:'n./v.',c:'平衡',s:'Keep a good balance.',cat:'work'},
{w:'budget',p:'n.',c:'预算',s:'We are over budget.',cat:'work'},
{w:'candidate',p:'n.',c:'候选人',s:'She is a strong candidate.',cat:'work'},
{w:'career',p:'n.',c:'职业',s:'He has a successful career.',cat:'work'},
{w:'challenge',p:'n./v.',c:'挑战',s:'I accept the challenge.',cat:'work'},
{w:'channel',p:'n.',c:'渠道/频道',s:'Change the TV channel.',cat:'work'},
{w:'communicate',p:'v.',c:'沟通',s:'We need to communicate better.',cat:'work'},
{w:'compete',p:'v.',c:'竞争',s:'They compete for the prize.',cat:'work'},
{w:'complex',p:'adj.',c:'复杂的',s:'This is a complex problem.',cat:'work'},
{w:'conference',p:'n.',c:'会议',s:'The conference starts at 9.',cat:'work'},
{w:'confidence',p:'n.',c:'信心',s:'I have confidence in you.',cat:'work'},
{w:'confirm',p:'v.',c:'确认',s:'Please confirm your booking.',cat:'work'},
{w:'consider',p:'v.',c:'考虑',s:'Consider all options.',cat:'work'},
{w:'cooperate',p:'v.',c:'合作',s:'Let\'s cooperate on this.',cat:'work'},
{w:'deadline',p:'n.',c:'截止日期',s:'The deadline is tomorrow.',cat:'work'},
{w:'decision',p:'n.',c:'决定',s:'Make a decision quickly.',cat:'work'},
{w:'department',p:'n.',c:'部门',s:'He works in the sales department.',cat:'work'},
{w:'efficient',p:'adj.',c:'高效的',s:'She is very efficient.',cat:'work'},
{w:'employ',p:'v.',c:'雇佣',s:'The company employs 200 people.',cat:'work'},
{w:'evaluate',p:'v.',c:'评估',s:'Evaluate the performance.',cat:'work'},
{w:'execute',p:'v.',c:'执行',s:'Execute the plan now.',cat:'work'},
{w:'explore',p:'v.',c:'探索',s:'Let\'s explore new ideas.',cat:'work'},
{w:'finance',p:'n.',c:'财务',s:'She studies finance.',cat:'work'},
{w:'improve',p:'v.',c:'改善',s:'I want to improve my English.',cat:'work'},
{w:'individual',p:'n./adj.',c:'个人',s:'Each individual is unique.',cat:'work'},
{w:'industry',p:'n.',c:'工业',s:'The tech industry is growing.',cat:'work'},
{w:'influence',p:'v./n.',c:'影响',s:'He has great influence.',cat:'work'},
{w:'initiative',p:'n.',c:'主动性',s:'Take the initiative.',cat:'work'},
{w:'negotiate',p:'v.',c:'谈判',s:'Let\'s negotiate the price.',cat:'work'},
{w:'objective',p:'n.',c:'目标',s:'What is your objective?',cat:'work'},
{w:'organize',p:'v.',c:'组织',s:'Organize your files.',cat:'work'},
{w:'policy',p:'n.',c:'政策',s:'What is the company policy?',cat:'work'},
{w:'potential',p:'adj./n.',c:'潜在的',s:'She has great potential.',cat:'work'},
{w:'progress',p:'n./v.',c:'进步',s:'You made good progress.',cat:'work'},
{w:'promote',p:'v.',c:'推广/晋升',s:'She was promoted last month.',cat:'work'},
{w:'proposal',p:'n.',c:'提案',s:'Submit your proposal by Friday.',cat:'work'},
{w:'quality',p:'n.',c:'质量',s:'The quality is excellent.',cat:'work'},
{w:'strategy',p:'n.',c:'策略',s:'We need a new strategy.',cat:'work'},
{w:'supervise',p:'v.',c:'监督',s:'He supervises the team.',cat:'work'},
{w:'target',p:'n.',c:'目标',s:'Hit the sales target.',cat:'work'},
{w:'update',p:'v./n.',c:'更新',s:'I need an update on this.',cat:'work'},
{w:'acid',p:'n.',c:'酸',s:'Lemons contain acid.',cat:'school'},
{w:'atom',p:'n.',c:'原子',s:'Everything is made of atoms.',cat:'school'},
{w:'biology',p:'n.',c:'生物',s:'I love biology class.',cat:'school'},
{w:'chemical',p:'adj./n.',c:'化学的',s:'This is a chemical reaction.',cat:'school'},
{w:'climate',p:'n.',c:'气候',s:'The climate is changing.',cat:'school'},
{w:'conclude',p:'v.',c:'结论',s:'What did you conclude?',cat:'school'},
{w:'data',p:'n.',c:'数据',s:'The data supports the theory.',cat:'school'},
{w:'define',p:'v.',c:'定义',s:'How do you define success?',cat:'school'},
{w:'degree',p:'n.',c:'学位/程度',s:'She has a degree in math.',cat:'school'},
{w:'detail',p:'n.',c:'细节',s:'Tell me the details.',cat:'school'},
{w:'discover',p:'v.',c:'发现',s:'Scientists discovered a new species.',cat:'school'},
{w:'effect',p:'n.',c:'效果/影响',s:'What is the effect?',cat:'school'},
{w:'energy',p:'n.',c:'能量/精力',s:'Solar energy is clean.',cat:'school'},
{w:'experiment',p:'n.',c:'实验',s:'The experiment was successful.',cat:'school'},
{w:'explain',p:'v.',c:'解释',s:'Can you explain this?',cat:'school'},
{w:'factor',p:'n.',c:'因素',s:'What is the main factor?',cat:'school'},
{w:'formula',p:'n.',c:'公式',s:'Use the right formula.',cat:'school'},
{w:'gene',p:'n.',c:'基因',s:'Genes determine traits.',cat:'school'},
{w:'gravity',p:'n.',c:'重力',s:'Gravity keeps us on the ground.',cat:'school'},
{w:'hypothesis',p:'n.',c:'假设',s:'Test the hypothesis.',cat:'school'},
{w:'lab',p:'n.',c:'实验室',s:'We work in the lab.',cat:'school'},
{w:'measure',p:'v.',c:'测量',s:'Measure the temperature.',cat:'school'},
{w:'method',p:'n.',c:'方法',s:'What method did you use?',cat:'school'},
{w:'observe',p:'v.',c:'观察',s:'Observe the changes carefully.',cat:'school'},
{w:'physics',p:'n.',c:'物理',s:'Physics is fascinating.',cat:'school'},
{w:'publish',p:'v.',c:'发表',s:'She published a paper.',cat:'school'},
{w:'research',p:'n./v.',c:'研究',s:'Do more research.',cat:'school'},
{w:'result',p:'n.',c:'结果',s:'The results are clear.',cat:'school'},
{w:'science',p:'n.',c:'科学',s:'Science is amazing.',cat:'school'},
{w:'theory',p:'n.',c:'理论',s:'In theory, it should work.',cat:'school'},
{w:'trace',p:'v./n.',c:'追踪',s:'Trace the source of the problem.',cat:'school'},
{w:'volume',p:'n.',c:'体积/音量',s:'Turn up the volume.',cat:'school'},
{w:'actor',p:'n.',c:'演员',s:'He is a famous actor.',cat:'media'},
{w:'art',p:'n.',c:'艺术',s:'I love modern art.',cat:'media'},
{w:'broadcast',p:'v./n.',c:'广播',s:'The news is broadcast daily.',cat:'media'},
{w:'camera',p:'n.',c:'相机',s:'Take a photo with the camera.',cat:'media'},
{w:'channel',p:'n.',c:'频道',s:'Switch to another channel.',cat:'media'},
{w:'character',p:'n.',c:'角色/字符',s:'The main character is brave.',cat:'media'},
{w:'director',p:'n.',c:'导演',s:'The director is brilliant.',cat:'media'},
{w:'documentary',p:'n.',c:'纪录片',s:'I watched a good documentary.',cat:'media'},
{w:'drama',p:'n.',c:'戏剧',s:'She enjoys drama.',cat:'media'},
{w:'edit',p:'v.',c:'编辑',s:'Edit the video carefully.',cat:'media'},
{w:'episode',p:'n.',c:'一集',s:'Watch the next episode.',cat:'media'},
{w:'fiction',p:'n.',c:'小说/虚构',s:'I prefer fiction.',cat:'media'},
{w:'film',p:'n.',c:'电影',s:'Let\'s watch a film.',cat:'media'},
{w:'headline',p:'n.',c:'标题',s:'Read the headlines.',cat:'media'},
{w:'journal',p:'n.',c:'期刊/日记',s:'She writes in her journal daily.',cat:'media'},
{w:'journalist',p:'n.',c:'记者',s:'The journalist asked tough questions.',cat:'media'},
{w:'magazine',p:'n.',c:'杂志',s:'I read this magazine monthly.',cat:'media'},
{w:'novel',p:'n.',c:'小说',s:'This novel is a bestseller.',cat:'media'},
{w:'poet',p:'n.',c:'诗人',s:'He is a famous poet.',cat:'media'},
{w:'publish',p:'v.',c:'出版',s:'The book was published last year.',cat:'media'},
{w:'script',p:'n.',c:'剧本',s:'Write a script for the show.',cat:'media'},
{w:'studio',p:'n.',c:'工作室',s:'We recorded in the studio.',cat:'media'},
{w:'stage',p:'n.',c:'舞台',s:'She performed on stage.',cat:'media'},
{w:'athlete',p:'n.',c:'运动员',s:'He is a professional athlete.',cat:'health'},
{w:'balance',p:'n.',c:'平衡',s:'Practice balance exercises.',cat:'health'},
{w:'breathe',p:'v.',c:'呼吸',s:'Breathe deeply and relax.',cat:'health'},
{w:'calorie',p:'n.',c:'卡路里',s:'Count your calories.',cat:'health'},
{w:'champion',p:'n.',c:'冠军',s:'She is the world champion.',cat:'health'},
{w:'coach',p:'n.',c:'教练',s:'The coach motivated the team.',cat:'health'},
{w:'diet',p:'n.',c:'饮食',s:'A balanced diet is important.',cat:'health'},
{w:'endurance',p:'n.',c:'耐力',s:'Build your endurance slowly.',cat:'health'},
{w:'energy',p:'n.',c:'精力',s:'I need more energy.',cat:'health'},
{w:'exercise',p:'n./v.',c:'锻炼',s:'Exercise every morning.',cat:'health'},
{w:'flexible',p:'adj.',c:'灵活的',s:'Yoga makes you flexible.',cat:'health'},
{w:'injury',p:'n.',c:'伤',s:'He recovered from his injury.',cat:'health'},
{w:'muscle',p:'n.',c:'肌肉',s:'Build muscle with weights.',cat:'health'},
{w:'nutrition',p:'n.',c:'营养',s:'Good nutrition is essential.',cat:'health'},
{w:'protein',p:'n.',c:'蛋白质',s:'Eat more protein.',cat:'health'},
{w:'recover',p:'v.',c:'恢复',s:'It takes time to recover.',cat:'health'},
{w:'stretch',p:'v.',c:'拉伸',s:'Stretch before running.',cat:'health'},
{w:'sweat',p:'v.',c:'流汗',s:'You sweat a lot in summer.',cat:'health'},
{w:'tournament',p:'n.',c:'锦标赛',s:'We won the tournament.',cat:'health'},
{w:'train',p:'v.',c:'训练',s:'Train hard every day.',cat:'health'},
{w:'vitamin',p:'n.',c:'维生素',s:'Take your vitamins daily.',cat:'health'},
{w:'warm',p:'adj.',c:'温暖的',s:'Do warm-up exercises first.',cat:'health'},
{w:'workout',p:'n.',c:'锻炼',s:'That was a great workout.',cat:'health'},
{w:'arrest',p:'v.',c:'逮捕',s:'The police arrested the thief.',cat:'society'},
{w:'court',p:'n.',c:'法庭',s:'The case goes to court.',cat:'society'},
{w:'crime',p:'n.',c:'犯罪',s:'Crime rates are decreasing.',cat:'society'},
{w:'criminal',p:'n.',c:'罪犯',s:'The criminal was caught.',cat:'society'},
{w:'evidence',p:'n.',c:'证据',s:'We need more evidence.',cat:'society'},
{w:'guilty',p:'adj.',c:'有罪的',s:'The jury found him guilty.',cat:'society'},
{w:'innocent',p:'adj.',c:'无辜的',s:'He proved he was innocent.',cat:'society'},
{w:'judge',p:'n./v.',c:'法官/判断',s:'The judge made the decision.',cat:'society'},
{w:'jury',p:'n.',c:'陪审团',s:'The jury reached a verdict.',cat:'society'},
{w:'justice',p:'n.',c:'正义',s:'Justice must be served.',cat:'society'},
{w:'lawyer',p:'n.',c:'律师',s:'Hire a good lawyer.',cat:'society'},
{w:'legal',p:'adj.',c:'合法的',s:'Is this legal?',cat:'society'},
{w:'permit',p:'v./n.',c:'许可',s:'You need a permit.',cat:'society'},
{w:'police',p:'n.',c:'警察',s:'Call the police!',cat:'society'},
{w:'punish',p:'v.',c:'惩罚',s:'He was punished for lying.',cat:'society'},
{w:'right',p:'n.',c:'权利',s:'Everyone has equal rights.',cat:'society'},
{w:'rule',p:'n.',c:'规则',s:'Follow the rules.',cat:'society'},
{w:'sentence',p:'n.',c:'判决/句子',s:'He received a light sentence.',cat:'society'},
{w:'statement',p:'n.',c:'声明',s:'Make a formal statement.',cat:'society'},
{w:'trial',p:'n.',c:'审判',s:'The trial begins tomorrow.',cat:'society'},
{w:'verdict',p:'n.',c:'裁决',s:'The verdict was not guilty.',cat:'society'},
{w:'witness',p:'n./v.',c:'证人/目击',s:'She witnessed the accident.',cat:'society'},
{w:'citizen',p:'n.',c:'公民',s:'Be a responsible citizen.',cat:'society'},
{w:'community',p:'n.',c:'社区',s:'Help your community.',cat:'society'},
{w:'culture',p:'n.',c:'文化',s:'Learn about different cultures.',cat:'society'},
{w:'democracy',p:'n.',c:'民主',s:'We value democracy.',cat:'society'},
{w:'society',p:'n.',c:'社会',s:'Our society is changing.',cat:'society'},
{w:'tradition',p:'n.',c:'传统',s:'Respect old traditions.',cat:'society'},
{w:'values',p:'n.',c:'价值观',s:'Family values matter.',cat:'society'},
{w:'vote',p:'v.',c:'投票',s:'Don\'t forget to vote.',cat:'society'},
{w:'apologize',p:'v.',c:'道歉',s:'I apologize for being late.',cat:'life'},
{w:'appointment',p:'n.',c:'预约',s:'I have a dentist appointment.',cat:'life'},
{w:'arrange',p:'v.',c:'安排',s:'Arrange the meeting for Tuesday.',cat:'life'},
{w:'bake',p:'v.',c:'烤',s:'Bake the cake for 30 minutes.',cat:'life'},
{w:'battery',p:'n.',c:'电池',s:'The battery is dead.',cat:'life'},
{w:'borrow',p:'v.',c:'借',s:'Can I borrow your pen?',cat:'life'},
{w:'brush',p:'v.',c:'刷',s:'Brush your teeth twice a day.',cat:'life'},
{w:'button',p:'n.',c:'按钮',s:'Press the red button.',cat:'life'},
{w:'carpet',p:'n.',c:'地毯',s:'The carpet needs cleaning.',cat:'life'},
{w:'ceiling',p:'n.',c:'天花板',s:'The ceiling is too low.',cat:'life'},
{w:'circuit',p:'n.',c:'电路',s:'The circuit is broken.',cat:'life'},
{w:'closet',p:'n.',c:'壁橱',s:'Hang your coat in the closet.',cat:'life'},
{w:'complain',p:'v.',c:'抱怨',s:'Don\'t complain about everything.',cat:'life'},
{w:'curtain',p:'n.',c:'窗帘',s:'Open the curtains.',cat:'life'},
{w:'decorate',p:'v.',c:'装饰',s:'Decorate the room for the party.',cat:'life'},
{w:'desert',p:'n.',c:'沙漠',s:'The desert is very hot.',cat:'life'},
{w:'drawer',p:'n.',c:'抽屉',s:'Put it in the top drawer.',cat:'life'},
{w:'engine',p:'n.',c:'引擎',s:'The engine makes a strange noise.',cat:'life'},
{w:'entrance',p:'n.',c:'入口',s:'Use the side entrance.',cat:'life'},
{w:'envelope',p:'n.',c:'信封',s:'Put the letter in an envelope.',cat:'life'},
{w:'error',p:'n.',c:'错误',s:'I made an error.',cat:'life'},
{w:'escape',p:'v.',c:'逃跑',s:'They escaped through the window.',cat:'life'},
{w:'fan',p:'n.',c:'风扇/粉丝',s:'Turn on the fan.',cat:'life'},
{w:'fingerprint',p:'n.',c:'指纹',s:'Leave your fingerprint here.',cat:'life'},
{w:'freeze',p:'v.',c:'冻结',s:'Don\'t freeze the vegetables.',cat:'life'},
{w:'garbage',p:'n.',c:'垃圾',s:'Take out the garbage.',cat:'life'},
{w:'grocery',p:'n.',c:'杂货',s:'Buy groceries on the way home.',cat:'life'},
{w:'hammer',p:'n.',c:'锤子',s:'Use a hammer to hang the picture.',cat:'life'},
{w:'helmet',p:'n.',c:'头盔',s:'Wear a helmet when cycling.',cat:'life'},
{w:'ingredient',p:'n.',c:'原料',s:'Mix all ingredients together.',cat:'life'},
{w:'knock',p:'v.',c:'敲',s:'Someone is knocking on the door.',cat:'life'},
{w:'laundry',p:'n.',c:'洗衣',s:'Do the laundry on weekends.',cat:'life'},
{w:'leak',p:'v.',c:'漏',s:'The pipe is leaking.',cat:'life'},
{w:'lock',p:'v./n.',c:'锁',s:'Lock the door when you leave.',cat:'life'},
{w:'mess',p:'n.',c:'混乱',s:'Your room is a mess.',cat:'life'},
{w:'mirror',p:'n.',c:'镜子',s:'Look in the mirror.',cat:'life'},
{w:'nap',p:'n.',c:'小睡',s:'Take a quick nap.',cat:'life'},
{w:'pencil',p:'n.',c:'铅笔',s:'I need a sharp pencil.',cat:'life'},
{w:'pipe',p:'n.',c:'管道',s:'The water pipe is frozen.',cat:'life'},
{w:'plug',p:'n.',c:'插头',s:'Plug in the charger.',cat:'life'},
{w:'pour',p:'v.',c:'倒',s:'Pour some tea for me.',cat:'life'},
{w:'recipe',p:'n.',c:'食谱',s:'Follow this recipe.',cat:'life'},
{w:'refrigerator',p:'n.',c:'冰箱',s:'Put the milk in the refrigerator.',cat:'life'},
{w:'remote',p:'n.',c:'遥控器',s:'Where is the remote?',cat:'life'},
{w:'screw',p:'n.',c:'螺丝',s:'Tighten the screw.',cat:'life'},
{w:'shelf',p:'n.',c:'架子',s:'Put books on the shelf.',cat:'life'},
{w:'shovel',p:'n.',c:'铲子',s:'Use a shovel to clear the snow.',cat:'life'},
{w:'sofa',p:'n.',c:'沙发',s:'Sit on the sofa.',cat:'life'},
{w:'stove',p:'n.',c:'炉子',s:'The soup is on the stove.',cat:'life'},
{w:'switch',p:'n./v.',c:'开关',s:'Turn off the switch.',cat:'life'},
{w:'tap',p:'n.',c:'水龙头',s:'Turn off the tap.',cat:'life'},
{w:'thermometer',p:'n.',c:'温度计',s:'Check the thermometer.',cat:'life'},
{w:'torch',p:'n.',c:'手电筒',s:'Use a torch in the dark.',cat:'life'},
{w:'trash',p:'n.',c:'垃圾',s:'Throw it in the trash.',cat:'life'},
{w:'vacuum',p:'n./v.',c:'吸尘器',s:'Vacuum the carpet.',cat:'life'},
{w:'wallet',p:'n.',c:'钱包',s:'I lost my wallet.',cat:'life'},
{w:'wax',p:'n.',c:'蜡',s:'The candle wax melted.',cat:'life'},
{w:'wrench',p:'n.',c:'扳手',s:'Use a wrench to fix the pipe.',cat:'life'},
];
// Batch 2: Extended vocabulary
const EXTRA_WORDS_2 = [
// Travel expanded
{w:'visa',p:'n.',c:'签证',s:'Do you need a visa to travel there?',cat:'travel'},
{w:'itinerary',p:'n.',c:'行程',s:'Here is our travel itinerary.',cat:'travel'},
{w:'souvenir',p:'n.',c:'纪念品',s:'I bought a souvenir for you.',cat:'travel'},
{w:'currency',p:'n.',c:'货币',s:'What currency do they use?',cat:'travel'},
{w:'embassy',p:'n.',c:'大使馆',s:'Call the embassy for help.',cat:'travel'},
{w:'souvenir',p:'n.',c:'纪念品',s:'I bought a souvenir for you.',cat:'travel'},
{w:'guidebook',p:'n.',c:'旅游指南',s:'Check the guidebook for info.',cat:'travel'},
{w:'check-in',p:'n.',c:'入住登记',s:'Check-in is at 3 PM.',cat:'travel'},
{w:'checkout',p:'n.',c:'退房',s:'Checkout is at noon.',cat:'travel'},
{w:'passport',p:'n.',c:'护照',s:'Show your passport at the counter.',cat:'travel'},
{w:'boarding',p:'n.',c:'登机',s:'Boarding starts in 30 minutes.',cat:'travel'},
{w:'departure',p:'n.',c:'出发',s:'Departure time is 10 AM.',cat:'travel'},
{w:'arrival',p:'n.',c:'到达',s:'Expected arrival is 3 PM.',cat:'travel'},
{w:'delay',p:'n./v.',c:'延误',s:'The flight is delayed by 2 hours.',cat:'travel'},
{w:'cancel',p:'v.',c:'取消',s:'They cancelled the flight.',cat:'travel'},
{w:'reserve',p:'v.',c:'预订',s:'I reserved a room online.',cat:'travel'},

// Work expanded
{w:'colleague',p:'n.',c:'同事',s:'My colleague helped me.',cat:'work'},
{w:'feedback',p:'n.',c:'反馈',s:'I appreciate your feedback.',cat:'work'},
{w:'brainstorm',p:'v.',c:'头脑风暴',s:'Let us brainstorm ideas.',cat:'work'},
{w:'deadline',p:'n.',c:'截止日期',s:'The deadline is next Friday.',cat:'work'},
{w:'overtime',p:'n.',c:'加班',s:'I worked overtime last night.',cat:'work'},
{w:'promotion',p:'n.',c:'晋升',s:'She got a promotion.',cat:'work'},
{w:'resume',p:'n.',c:'简历',s:'Update your resume regularly.',cat:'work'},
{w:'interview',p:'n.',c:'面试',s:'The interview went well.',cat:'work'},
{w:'salary',p:'n.',c:'薪水',s:'My salary was increased.',cat:'work'},
{w:'bonus',p:'n.',c:'奖金',s:'I got a year-end bonus.',cat:'work'},
{w:'pension',p:'n.',c:'养老金',s:'Save for your pension.',cat:'work'},
{w:'launch',p:'v.',c:'发布',s:'We will launch the product soon.',cat:'work'},
{w:'negotiate',p:'v.',c:'谈判',s:'We need to negotiate terms.',cat:'work'},
{w:'signature',p:'n.',c:'签名',s:'Put your signature here.',cat:'work'},
{w:'agenda',p:'n.',c:'议程',s:'What is on the agenda?',cat:'work'},
{w:'Minutes',p:'n.',c:'会议纪要',s:'Send the meeting minutes.',cat:'work'},
{w:'presentation',p:'n.',c:'演示',s:'Your presentation was great.',cat:'work'},
{w:'spreadsheet',p:'n.',c:'电子表格',s:'Update the spreadsheet.',cat:'work'},
{w:'revenue',p:'n.',c:'收入',s:'Revenue increased this quarter.',cat:'work'},
{w:'expense',p:'n.',c:'支出',s:'Track your expenses.',cat:'work'},
{w:'invoice',p:'n.',c:'发票',s:'Send the invoice to the client.',cat:'work'},
{w:'client',p:'n.',c:'客户',s:'The client is very satisfied.',cat:'work'},
{w:'vendor',p:'n.',c:'供应商',s:'Contact the vendor for support.',cat:'work'},
{w:'startup',p:'n.',c:'初创公司',s:'She works at a startup.',cat:'work'},
{w:'entrepreneur',p:'n.',c:'企业家',s:'He is a young entrepreneur.',cat:'work'},
{w:'freelance',p:'adj./n.',c:'自由职业',s:'I do freelance work.',cat:'work'},

// Health expanded
{w:'checkup',p:'n.',c:'体检',s:'Get a regular checkup.',cat:'health'},
{w:'therapy',p:'n.',c:'治疗',s:'She is in therapy.',cat:'health'},
{w:'surgery',p:'n.',c:'手术',s:'He needs surgery.',cat:'health'},
{w:'infection',p:'n.',c:'感染',s:'The infection is healing.',cat:'health'},
{w:'vaccine',p:'n.',c:'疫苗',s:'Get your flu vaccine.',cat:'health'},
{w:'chronic',p:'adj.',c:'慢性的',s:'It is a chronic condition.',cat:'health'},
{w:'symptom',p:'n.',c:'症状',s:'Describe your symptoms.',cat:'health'},
{w:'diagnosis',p:'n.',c:'诊断',s:'The diagnosis was positive.',cat:'health'},
{w:'recovery',p:'n.',c:'康复',s:'Her recovery is going well.',cat:'health'},
{w:'prescription',p:'n.',c:'处方',s:'I need to refill my prescription.',cat:'health'},
{w:'vitamin',p:'n.',c:'维生素',s:'Take vitamins daily.',cat:'health'},
{w:'nutrition',p:'n.',c:'营养',s:'Good nutrition is important.',cat:'health'},
{w:'hygiene',p:'n.',c:'卫生',s:'Personal hygiene matters.',cat:'health'},
{w:'wellness',p:'n.',c:'健康',s:'She focuses on wellness.',cat:'health'},
{w:'mental',p:'adj.',c:'心理的',s:'Mental health is important.',cat:'health'},
{w:'physical',p:'adj.',c:'身体的',s:'Physical exercise is essential.',cat:'health'},

// Food expanded
{w:'appetizer',p:'n.',c:'开胃菜',s:'Let us order an appetizer.',cat:'food2'},
{w:'beverage',p:'n.',c:'饮料',s:'Choose your beverage.',cat:'food2'},
{w:'cuisine',p:'n.',c:'菜系',s:'Italian cuisine is popular.',cat:'food2'},
{w:'dessert',p:'n.',c:'甜点',s:'What is for dessert?',cat:'food2'},
{w:'ingredient',p:'n.',c:'原料',s:'Mix all ingredients.',cat:'food2'},
{w:'recipe',p:'n.',c:'食谱',s:'Follow this recipe.',cat:'food2'},
{w:'spicy',p:'adj.',c:'辣的',s:'I like spicy food.',cat:'food2'},
{w:'sour',p:'adj.',c:'酸的',s:'The lemon is sour.',cat:'food2'},
{w:'bitter',p:'adj.',c:'苦的',s:'Coffee can be bitter.',cat:'food2'},
{w:'roasted',p:'adj.',c:'烤的',s:'I like roasted chicken.',cat:'food2'},
{w:'steamed',p:'adj.',c:'蒸的',s:'Steamed vegetables are healthy.',cat:'food2'},
{w:'fried',p:'adj.',c:'炸的',s:'Fried food is tasty but unhealthy.',cat:'food2'},
{w:'raw',p:'adj.',c:'生的',s:'Can I eat raw fish?',cat:'food2'},
{w:'fresh',p:'adj.',c:'新鲜的',s:'The fish is fresh today.',cat:'food2'},
{w:'organic',p:'adj.',c:'有机的',s:'I buy organic vegetables.',cat:'food2'},
{w:'beverage',p:'n.',c:'饮料',s:'Choose your beverage.',cat:'food2'},
{w:'snack',p:'n.',c:'零食',s:'I had a quick snack.',cat:'food2'},
{w:'bartender',p:'n.',c:'调酒师',s:'The bartender makes great cocktails.',cat:'food2'},
{w:'waiter',p:'n.',c:'服务员',s:'The waiter brought the menu.',cat:'food2'},
{w:'menu',p:'n.',c:'菜单',s:'Can I see the menu?',cat:'food2'},
{w:'tip',p:'n.',c:'小费',s:'Leave a tip for the waiter.',cat:'food2'},
{w:'bill',p:'n.',c:'账单',s:'Can I have the bill?',cat:'food2'},

// Technology expanded
{w:'software',p:'n.',c:'软件',s:'Install the software.',cat:'tech'},
{w:'hardware',p:'n.',c:'硬件',s:'The hardware needs upgrading.',cat:'tech'},
{w:'download',p:'v.',c:'下载',s:'Download the app now.',cat:'tech'},
{w:'upload',p:'v.',c:'上传',s:'Upload the file here.',cat:'tech'},
{w:'password',p:'n.',c:'密码',s:'Change your password.',cat:'tech'},
{w:'username',p:'n.',c:'用户名',s:'Enter your username.',cat:'tech'},
{w:'account',p:'n.',c:'账号',s:'Create a new account.',cat:'tech'},
{w:'setting',p:'n.',c:'设置',s:'Check your settings.',cat:'tech'},
{w:'update',p:'v./n.',c:'更新',s:'Install the latest update.',cat:'tech'},
{w:'backup',p:'n./v.',c:'备份',s:'Make a backup of your files.',cat:'tech'},
{w:'database',p:'n.',c:'数据库',s:'The database is updated.',cat:'tech'},
{w:'network',p:'n.',c:'网络',s:'The network is down.',cat:'tech'},
{w:'server',p:'n.',c:'服务器',s:'The server is offline.',cat:'tech'},
{w:'browser',p:'n.',c:'浏览器',s:'Open your browser.',cat:'tech'},
{w:'website',p:'n.',c:'网站',s:'Visit our website.',cat:'tech'},
{w:'application',p:'n.',c:'应用',s:'Download the application.',cat:'tech'},
{w:'storage',p:'n.',c:'存储',s:'Not enough storage space.',cat:'tech'},
{w:'memory',p:'n.',c:'内存',s:'My phone has 128GB memory.',cat:'tech'},
{w:'screen',p:'n.',c:'屏幕',s:'The screen is cracked.',cat:'tech'},
{w:'keyboard',p:'n.',c:'键盘',s:'Type on the keyboard.',cat:'tech'},
{w:'headphone',p:'n.',c:'耳机',s:'Put on your headphones.',cat:'tech'},
{w:'charger',p:'n.',c:'充电器',s:'I forgot my charger.',cat:'tech'},
{w:'battery',p:'n.',c:'电池',s:'My battery is low.',cat:'tech'},
{w:'bluetooth',p:'n.',c:'蓝牙',s:'Turn on Bluetooth.',cat:'tech'},
{w:'wifi',p:'n.',c:'无线网络',s:'Connect to WiFi.',cat:'tech'},

// Emotion expanded
{w:'jealous',p:'adj.',c:'嫉妒的',s:'Do not be jealous of others.',cat:'emotion'},
{w:'ashamed',p:'adj.',c:'羞愧的',s:'I am ashamed of my mistake.',cat:'emotion'},
{w:'relieved',p:'adj.',c:'松了一口气的',s:'I am relieved it is over.',cat:'emotion'},
{w:'anxious',p:'adj.',c:'焦虑的',s:'I feel anxious before exams.',cat:'emotion'},
{w:'depressed',p:'adj.',c:'抑郁的',s:'She feels depressed lately.',cat:'emotion'},
{w:'delighted',p:'adj.',c:'高兴的',s:'I am delighted to see you.',cat:'emotion'},
{w:'frustrated',p:'adj.',c:'沮丧的',s:'He is frustrated with work.',cat:'emotion'},
{w:'grateful',p:'adj.',c:'感激的',s:'I am grateful for your help.',cat:'emotion'},
{w:'enthusiastic',p:'adj.',c:'热情的',s:'She is enthusiastic about learning.',cat:'emotion'},
{w:'indifferent',p:'adj.',c:'冷漠的',s:'He seems indifferent to the result.',cat:'emotion'},
{w:'sympathy',p:'n.',c:'同情',s:'I feel sympathy for her.',cat:'emotion'},
{w:'empathy',p:'n.',c:'共情',s:'Empathy builds relationships.',cat:'emotion'},
{w:'nostalgia',p:'n.',c:'怀旧',s:'I feel nostalgia for my childhood.',cat:'emotion'},

// Daily life expanded
{w:'appointment',p:'n.',c:'预约',s:'I have a doctor appointment.',cat:'life'},
{w:'schedule',p:'n.',c:'日程',s:'Check my schedule.',cat:'life'},
{w:'routine',p:'n.',c:'日常',s:'My morning routine.',cat:'life'},
{w:'habit',p:'n.',c:'习惯',s:'Develop good habits.',cat:'life'},
{w:'hobby',p:'n.',c:'爱好',s:'Reading is my hobby.',cat:'life'},
{w:'collection',p:'n.',c:'收藏',s:'I have a stamp collection.',cat:'life'},
{w:'garden',p:'n.',c:'花园',s:'She works in the garden.',cat:'life'},
{w:'garage',p:'n.',c:'车库',s:'Park in the garage.',cat:'life'},
{w:'balcony',p:'n.',c:'阳台',s:'Have coffee on the balcony.',cat:'life'},
{w:'neighbor',p:'n.',c:'邻居',s:'My neighbor is friendly.',cat:'life'},
{w:'community',p:'n.',c:'社区',s:'Join the community group.',cat:'life'},
{w:'volunteer',p:'n./v.',c:'志愿者',s:'I volunteer at the shelter.',cat:'life'},
{w:'charity',p:'n.',c:'慈善',s:'Donate to charity.',cat:'life'},
{w:'donation',p:'n.',c:'捐赠',s:'Make a donation today.',cat:'life'},
{w:'recycle',p:'v.',c:'回收',s:'Recycle plastic bottles.',cat:'life'},
{w:'garbage',p:'n.',c:'垃圾',s:'Take out the garbage.',cat:'life'},

// Education expanded
{w:'assignment',p:'n.',c:'作业',s:'Submit your assignment.',cat:'school'},
{w:'scholarship',p:'n.',c:'奖学金',s:'She won a scholarship.',cat:'school'},
{w:'lecture',p:'n.',c:'讲座',s:'The lecture was informative.',cat:'school'},
{w:'seminar',p:'n.',c:'研讨会',s:'Attend the seminar.',cat:'school'},
{w:'campus',p:'n.',c:'校园',s:'The campus is beautiful.',cat:'school'},
{w:'tuition',p:'n.',c:'学费',s:'Tuition is expensive.',cat:'school'},
{w:'graduation',p:'n.',c:'毕业',s:'Her graduation is in June.',cat:'school'},
{w:'enroll',p:'v.',c:'注册',s:'Enroll in the course.',cat:'school'},
{w:'certificate',p:'n.',c:'证书',s:'I got a completion certificate.',cat:'school'},
{w:'quiz',p:'n.',c:'小测',s:'We have a quiz tomorrow.',cat:'school'},
{w:'semester',p:'n.',c:'学期',s:'The semester starts in September.',cat:'school'},
{w:'textbook',p:'n.',c:'课本',s:'Buy the textbook online.',cat:'school'},
{w:'library',p:'n.',c:'图书馆',s:'Study in the library.',cat:'school'},

// Weather expanded
{w:'breeze',p:'n.',c:'微风',s:'A cool breeze is blowing.',cat:'weather'},
{w:'storm',p:'n.',c:'暴风雨',s:'The storm is coming.',cat:'weather'},
{w:'thunder',p:'n.',c:'雷',s:'The thunder was loud.',cat:'weather'},
{w:'lightning',p:'n.',c:'闪电',s:'Lightning struck the tree.',cat:'weather'},
{w:'fog',p:'n.',c:'雾',s:'Drive carefully in the fog.',cat:'weather'},
{w:'flood',p:'n.',c:'洪水',s:'The flood damaged homes.',cat:'weather'},
{w:'drought',p:'n.',c:'干旱',s:'The drought lasted months.',cat:'weather'},
{w:'humidity',p:'n.',c:'湿度',s:'The humidity is high today.',cat:'weather'},
{w:'forecast',p:'n.',c:'预报',s:'Check the weather forecast.',cat:'weather'},
{w:'climate',p:'n.',c:'气候',s:'The climate is changing.',cat:'weather'},
{w:'temperature',p:'n.',c:'温度',s:'The temperature dropped.',cat:'weather'},
{w:'freeze',p:'v.',c:'冻结',s:'The lake froze overnight.',cat:'weather'},

// Animals expanded
{w:'puppy',p:'n.',c:'小狗',s:'The puppy is so cute.',cat:'animals'},
{w:'kitten',p:'n.',c:'小猫',s:'I adopted a kitten.',cat:'animals'},
{w:'rabbit',p:'n.',c:'兔子',s:'The rabbit hops fast.',cat:'animals'},
{w:'monkey',p:'n.',c:'猴子',s:'Monkeys love bananas.',cat:'animals'},
{w:'elephant',p:'n.',c:'大象',s:'Elephants are huge.',cat:'animals'},
{w:'tiger',p:'n.',c:'老虎',s:'The tiger is hunting.',cat:'animals'},
{w:'penguin',p:'n.',c:'企鹅',s:'Penguins live in cold places.',cat:'animals'},
{w:'dolphin',p:'n.',c:'海豚',s:'Dolphins are smart.',cat:'animals'},
{w:'butterfly',p:'n.',c:'蝴蝶',s:'The butterfly is colorful.',cat:'animals'},
{w:'spider',p:'n.',c:'蜘蛛',s:'A spider made a web.',cat:'animals'},
{w:'snake',p:'n.',c:'蛇',s:'The snake slithered away.',cat:'animals'},
{w:'duck',p:'n.',c:'鸭子',s:'Ducks swim in the pond.',cat:'animals'},
{w:'sheep',p:'n.',c:'羊',s:'The sheep are grazing.',cat:'animals'},
{w:'goat',p:'n.',c:'山羊',s:'Goats climb mountains.',cat:'animals'},

// Clothing expanded
{w:'sneakers',p:'n.',c:'运动鞋',s:'I bought new sneakers.',cat:'clothing'},
{w:'sandals',p:'n.',c:'凉鞋',s:'Wear sandals in summer.',cat:'clothing'},
{w:'boots',p:'n.',c:'靴子',s:'Wear boots in winter.',cat:'clothing'},
{w:'jacket',p:'n.',c:'外套',s:'Put on a jacket.',cat:'clothing'},
{w:'sweater',p:'n.',c:'毛衣',s:'She wore a warm sweater.',cat:'clothing'},
{w:'jeans',p:'n.',c:'牛仔裤',s:'I love these jeans.',cat:'clothing'},
{w:'suit',p:'n.',c:'西装',s:'He wore a suit to the interview.',cat:'clothing'},
{w:'tie',p:'n.',c:'领带',s:'He loosened his tie.',cat:'clothing'},
{w:'gloves',p:'n.',c:'手套',s:'Wear gloves in cold weather.',cat:'clothing'},
{w:'scarf',p:'n.',c:'围巾',s:'Wrap a scarf around your neck.',cat:'clothing'},
{w:'uniform',p:'n.',c:'制服',s:'Students wear uniforms.',cat:'clothing'},
{w:'pajamas',p:'n.',c:'睡衣',s:'Change into pajamas.',cat:'clothing'},
{w:'underwear',p:'n.',c:'内衣',s:'Buy new underwear.',cat:'clothing'},
{w:'collar',p:'n.',c:'衣领',s:'The collar is too tight.',cat:'clothing'},
{w:'pocket',p:'n.',c:'口袋',s:'Put it in your pocket.',cat:'clothing'},

// Body expanded
{w:'shoulder',p:'n.',c:'肩膀',s:'My shoulder hurts.',cat:'body'},
{w:'elbow',p:'n.',c:'肘',s:'He rested his elbow on the table.',cat:'body'},
{w:'wrist',p:'n.',c:'手腕',s:'She wore a watch on her wrist.',cat:'body'},
{w:'ankle',p:'n.',c:'脚踝',s:'I twisted my ankle.',cat:'body'},
{w:'knee',p:'n.',c:'膝盖',s:'My knee is sore.',cat:'body'},
{w:'hip',p:'n.',c:'臀部',s:'He broke his hip.',cat:'body'},
{w:'waist',p:'n.',c:'腰',s:'Measure your waist.',cat:'body'},
{w:'chest',p:'n.',c:'胸',s:'He has chest pain.',cat:'body'},
{w:'chin',p:'n.',c:'下巴',s:'Rest your chin on your hand.',cat:'body'},
{w:'forehead',p:'n.',c:'额头',s:'Wipe your forehead.',cat:'body'},
{w:'eyebrow',p:'n.',c:'眉毛',s:'She raised an eyebrow.',cat:'body'},
{w:'eyelash',p:'n.',c:'睫毛',s:'She has long eyelashes.',cat:'body'},
{w:'tongue',p:'n.',c:'舌头',s:'Burn your tongue on hot food.',cat:'body'},
{w:'throat',p:'n.',c:'喉咙',s:'My throat is sore.',cat:'body'},
{w:'lung',p:'n.',c:'肺',s:'Smoking damages your lungs.',cat:'body'},
{w:'kidney',p:'n.',c:'肾',s:'He donated a kidney.',cat:'body'},

// Transport expanded
{w:'subway',p:'n.',c:'地铁',s:'Take the subway downtown.',cat:'transport'},
{w:'highway',p:'n.',c:'高速公路',s:'The highway is busy.',cat:'transport'},
{w:'intersection',p:'n.',c:'十字路口',s:'Stop at the intersection.',cat:'transport'},
{w:'roundabout',p:'n.',c:'环岛',s:'Enter the roundabout.',cat:'transport'},
{w:'parking',p:'n.',c:'停车',s:'Find a parking spot.',cat:'transport'},
{w:'ticket',p:'n.',c:'票',s:'Buy a train ticket.',cat:'transport'},
{w:'lane',p:'n.',c:'车道',s:'Stay in your lane.',cat:'transport'},
{w:'traffic',p:'n.',c:'交通',s:'Traffic is heavy today.',cat:'transport'},
{w:'pedestrian',p:'n.',c:'行人',s:'Watch for pedestrians.',cat:'transport'},
{w:'helmet',p:'n.',c:'头盔',s:'Wear a helmet on a bike.',cat:'transport'},
{w:'trunk',p:'n.',c:'后备箱',s:'Put luggage in the trunk.',cat:'transport'},
{w:'wheel',p:'n.',c:'轮子',s:'The wheel is flat.',cat:'transport'},
{w:'engine',p:'n.',c:'引擎',s:'The engine started.',cat:'transport'},
{w:'brake',p:'n.',c:'刹车',s:'Step on the brake.',cat:'transport'},
{w:'mirror',p:'n.',c:'后视镜',s:'Check your mirror.',cat:'transport'},

// Society expanded
{w:'generation',p:'n.',c:'代',s:'The younger generation.',cat:'society'},
{w:'religion',p:'n.',c:'宗教',s:'Respect all religions.',cat:'society'},
{w:'festival',p:'n.',c:'节日',s:'The spring festival is coming.',cat:'society'},
{w:'ceremony',p:'n.',c:'仪式',s:'The wedding ceremony was beautiful.',cat:'society'},
{w:'wedding',p:'n.',c:'婚礼',s:'Their wedding is next month.',cat:'society'},
{w:'funeral',p:'n.',c:'葬礼',s:'The funeral was solemn.',cat:'society'},
{w:'birthday',p:'n.',c:'生日',s:'Happy birthday to you!',cat:'society'},
{w:'anniversary',p:'n.',c:'纪念日',s:'Their anniversary is today.',cat:'society'},
{w:'holiday',p:'n.',c:'假日',s:'Enjoy your holiday!',cat:'society'},
{w:'celebrate',p:'v.',c:'庆祝',s:'Let us celebrate together.',cat:'society'},
{w:'reunion',p:'n.',c:'团聚',s:'Family reunion at New Year.',cat:'society'},
{w:'ancestor',p:'n.',c:'祖先',s:'They honor their ancestors.',cat:'society'},
{w:'heritage',p:'n.',c:'遗产',s:'Cultural heritage is precious.',cat:'society'},
{w:'diversity',p:'n.',c:'多样性',s:'Diversity makes us stronger.',cat:'society'},

// Sports expanded
{w:'soccer',p:'n.',c:'足球',s:'Play soccer after school.',cat:'health'},
{w:'basketball',p:'n.',c:'篮球',s:'He loves basketball.',cat:'health'},
{w:'tennis',p:'n.',c:'网球',s:'Play tennis on weekends.',cat:'health'},
{w:'swimming',p:'n.',c:'游泳',s:'Swimming is good exercise.',cat:'health'},
{w:'cycling',p:'n.',c:'骑行',s:'Cycling is eco-friendly.',cat:'health'},
{w:'jogging',p:'n.',c:'慢跑',s:'Go jogging every morning.',cat:'health'},
{w:'yoga',p:'n.',c:'瑜伽',s:'She practices yoga daily.',cat:'health'},
{w:'skiing',p:'n.',c:'滑雪',s:'Go skiing in winter.',cat:'health'},
{w:'fishing',p:'n.',c:'钓鱼',s:'He enjoys fishing.',cat:'health'},
{w:'boxing',p:'n.',c:'拳击',s:'Boxing requires strength.',cat:'health'},
{w:'referee',p:'n.',c:'裁判',s:'The referee blew the whistle.',cat:'health'},
{w:'score',p:'n.',c:'比分',s:'The score is 2 to 1.',cat:'health'},
{w:'team',p:'n.',c:'队伍',s:'Our team won the game.',cat:'health'},
{w:'goal',p:'n.',c:'进球/目标',s:'He scored a goal.',cat:'health'},
{w:'medal',p:'n.',c:'奖牌',s:'She won a gold medal.',cat:'health'},

// Media expanded
{w:'podcast',p:'n.',c:'播客',s:'I listen to podcasts daily.',cat:'media'},
{w:'vlog',p:'n.',c:'视频博客',s:'She posts vlogs weekly.',cat:'media'},
{w:'hashtag',p:'n.',c:'话题标签',s:'Use a hashtag to trend.',cat:'media'},
{w:'comment',p:'n./v.',c:'评论',s:'Leave a comment below.',cat:'media'},
{w:'share',p:'v.',c:'分享',s:'Share this with friends.',cat:'media'},
{w:'subscribe',p:'v.',c:'订阅',s:'Subscribe to my channel.',cat:'media'},
{w:'notification',p:'n.',c:'通知',s:'Turn off notifications.',cat:'media'},
{w:'message',p:'n.',c:'消息',s:'Send me a message.',cat:'media'},
{w:'contact',p:'n./v.',c:'联系人',s:'Add me to your contacts.',cat:'media'},
{w:'profile',p:'n.',c:'个人资料',s:'Update your profile.',cat:'media'},
{w:'post',p:'n./v.',c:'帖子',s:'She posted a photo.',cat:'media'},
{w:'follower',p:'n.',c:'粉丝',s:'She has many followers.',cat:'media'},
{w:'influencer',p:'n.',c:'网红',s:'She is a famous influencer.',cat:'media'},
{w:'streaming',p:'n.',c:'流媒体',s:'Streaming is very popular.',cat:'media'},
{w:'advertisement',p:'n.',c:'广告',s:'The advertisement is everywhere.',cat:'media'},

// Law expanded
{w:'contract',p:'n.',c:'合同',s:'Sign the contract here.',cat:'society'},
{w:'agreement',p:'n.',c:'协议',s:'We reached an agreement.',cat:'society'},
{w:'copyright',p:'n.',c:'版权',s:'Copyright protects creators.',cat:'society'},
{w:'permit',p:'n.',c:'许可证',s:'You need a work permit.',cat:'society'},
{w:'license',p:'n.',c:'执照',s:'She got her driver license.',cat:'society'},
{w:'property',p:'n.',c:'财产',s:'Protect your property.',cat:'society'},
{w:'rent',p:'n./v.',c:'租金',s:'Pay rent on the first.',cat:'society'},
{w:'mortgage',p:'n.',c:'房贷',s:'They paid off their mortgage.',cat:'society'},
{w:'insurance',p:'n.',c:'保险',s:'Buy health insurance.',cat:'society'},
{w:'tax',p:'n.',c:'税',s:'File your taxes on time.',cat:'society'},
{w:'invest',p:'v.',c:'投资',s:'Invest in your future.',cat:'society'},
{w:'budget',p:'n.',c:'预算',s:'Stick to your budget.',cat:'society'},
{w:'debt',p:'n.',c:'债务',s:'Pay off your debt.',cat:'society'},
{w:'saving',p:'n.',c:'存款',s:'Build your savings.',cat:'society'},
{w:'loan',p:'n.',c:'贷款',s:'Apply for a student loan.',cat:'society'},
{w:'interest',p:'n.',c:'利息',s:'The interest rate is low.',cat:'society'},
];
