// Additional vocabulary - English Trainer v2
const EXTRA_WORDS = [
{w:'accept',p:'v.',c:'接受',s:'Please accept my apology.',cat:'work'},
{w:'account',p:'n.',c:'账户',s:'I opened a bank account.',cat:'work'},
{w:'achieve',p:'v.',c:'实现/达到',s:'She achieved her goal.',cat:'work'},
{w:'adapt',p:'v.',c:'适应',s:'You must adapt to changes.',cat:'work'},
{w:'advantage',p:'n.',c:'优势',s:'What is the advantage?',cat:'work'},
{w:'ambition',p:'n.',c:'野心/抱负',s:'He has great ambition.',cat:'work'},
{w:'analyze',p:'v.',c:'分析',s:'Analyze the data carefully.',cat:'work'},
{w:'apply',p:'v.',c:'申请',s:'Apply for the job online.',cat:'work'},
{w:'approach',p:'v./n.',c:'接近/方法',s:'A new approach is needed.',cat:'work'},
{w:'assign',p:'v.',c:'分配',s:'The teacher assigned homework.',cat:'work'},
{w:'assist',p:'v.',c:'协助',s:'Can you assist me?',cat:'work'},
{w:'assume',p:'v.',c:'假设',s:'Don\'t assume anything.',cat:'work'},
{w:'attend',p:'v.',c:'出席',s:'Please attend the meeting.',cat:'work'},
{w:'authority',p:'n.',c:'权威',s:'Who is in authority here?',cat:'work'},
{w:'available',p:'adj.',c:'可用的',s:'Is this room available?',cat:'work'},
{w:'average',p:'adj./n.',c:'平均的',s:'The average score is 80.',cat:'work'},
{w:'balance',p:'n./v.',c:'平衡',s:'Keep a good balance.',cat:'work'},
{w:'budget',p:'n.',c:'预算',s:'We are over budget.',cat:'work'},
{w:'candidate',p:'n.',c:'候选人',s:'She is a strong candidate.',cat:'work'},
{w:'career',p:'n.',c:'职业',s:'He has a successful career.',cat:'work'},
{w:'challenge',p:'n./v.',c:'挑战',s:'I accept the challenge.',cat:'work'},
{w:'channel',p:'n.',c:'渠道/频道',s:'Change the TV channel.',cat:'work'},
{w:'communicate',p:'v.',c:'沟通',s:'We need to communicate better.',cat:'work'},
{w:'compete',p:'v.',c:'竞争',s:'They compete for the prize.',cat:'work'},
{w:'complex',p:'adj.',c:'复杂的',s:'This is a complex problem.',cat:'work'},
{w:'conference',p:'n.',c:'会议',s:'The conference starts at 9.',cat:'work'},
{w:'confidence',p:'n.',c:'信心',s:'I have confidence in you.',cat:'work'},
{w:'confirm',p:'v.',c:'确认',s:'Please confirm your booking.',cat:'work'},
{w:'consider',p:'v.',c:'考虑',s:'Consider all options.',cat:'work'},
{w:'cooperate',p:'v.',c:'合作',s:'Let\'s cooperate on this.',cat:'work'},
{w:'deadline',p:'n.',c:'截止日期',s:'The deadline is tomorrow.',cat:'work'},
{w:'decision',p:'n.',c:'决定',s:'Make a decision quickly.',cat:'work'},
{w:'department',p:'n.',c:'部门',s:'He works in the sales department.',cat:'work'},
{w:'efficient',p:'adj.',c:'高效的',s:'She is very efficient.',cat:'work'},
{w:'employ',p:'v.',c:'雇佣',s:'The company employs 200 people.',cat:'work'},
{w:'evaluate',p:'v.',c:'评估',s:'Evaluate the performance.',cat:'work'},
{w:'execute',p:'v.',c:'执行',s:'Execute the plan now.',cat:'work'},
{w:'explore',p:'v.',c:'探索',s:'Let\'s explore new ideas.',cat:'work'},
{w:'finance',p:'n.',c:'财务',s:'She studies finance.',cat:'work'},
{w:'improve',p:'v.',c:'改善',s:'I want to improve my English.',cat:'work'},
{w:'individual',p:'n./adj.',c:'个人',s:'Each individual is unique.',cat:'work'},
{w:'industry',p:'n.',c:'工业',s:'The tech industry is growing.',cat:'work'},
{w:'influence',p:'v./n.',c:'影响',s:'He has great influence.',cat:'work'},
{w:'initiative',p:'n.',c:'主动性',s:'Take the initiative.',cat:'work'},
{w:'negotiate',p:'v.',c:'谈判',s:'Let\'s negotiate the price.',cat:'work'},
{w:'objective',p:'n.',c:'目标',s:'What is your objective?',cat:'work'},
{w:'organize',p:'v.',c:'组织',s:'Organize your files.',cat:'work'},
{w:'policy',p:'n.',c:'政策',s:'What is the company policy?',cat:'work'},
{w:'potential',p:'adj./n.',c:'潜在的',s:'She has great potential.',cat:'work'},
{w:'progress',p:'n./v.',c:'进步',s:'You made good progress.',cat:'work'},
{w:'promote',p:'v.',c:'推广/晋升',s:'She was promoted last month.',cat:'work'},
{w:'proposal',p:'n.',c:'提案',s:'Submit your proposal by Friday.',cat:'work'},
{w:'quality',p:'n.',c:'质量',s:'The quality is excellent.',cat:'work'},
{w:'strategy',p:'n.',c:'策略',s:'We need a new strategy.',cat:'work'},
{w:'supervise',p:'v.',c:'监督',s:'He supervises the team.',cat:'work'},
{w:'target',p:'n.',c:'目标',s:'Hit the sales target.',cat:'work'},
{w:'update',p:'v./n.',c:'更新',s:'I need an update on this.',cat:'work'},
{w:'acid',p:'n.',c:'酸',s:'Lemons contain acid.',cat:'school'},
{w:'atom',p:'n.',c:'原子',s:'Everything is made of atoms.',cat:'school'},
{w:'biology',p:'n.',c:'生物',s:'I love biology class.',cat:'school'},
{w:'chemical',p:'adj./n.',c:'化学的',s:'This is a chemical reaction.',cat:'school'},
{w:'climate',p:'n.',c:'气候',s:'The climate is changing.',cat:'school'},
{w:'conclude',p:'v.',c:'结论',s:'What did you conclude?',cat:'school'},
{w:'data',p:'n.',c:'数据',s:'The data supports the theory.',cat:'school'},
{w:'define',p:'v.',c:'定义',s:'How do you define success?',cat:'school'},
{w:'degree',p:'n.',c:'学位/程度',s:'She has a degree in math.',cat:'school'},
{w:'detail',p:'n.',c:'细节',s:'Tell me the details.',cat:'school'},
{w:'discover',p:'v.',c:'发现',s:'Scientists discovered a new species.',cat:'school'},
{w:'effect',p:'n.',c:'效果/影响',s:'What is the effect?',cat:'school'},
{w:'energy',p:'n.',c:'能量/精力',s:'Solar energy is clean.',cat:'school'},
{w:'experiment',p:'n.',c:'实验',s:'The experiment was successful.',cat:'school'},
{w:'explain',p:'v.',c:'解释',s:'Can you explain this?',cat:'school'},
{w:'factor',p:'n.',c:'因素',s:'What is the main factor?',cat:'school'},
{w:'formula',p:'n.',c:'公式',s:'Use the right formula.',cat:'school'},
{w:'gene',p:'n.',c:'基因',s:'Genes determine traits.',cat:'school'},
{w:'gravity',p:'n.',c:'重力',s:'Gravity keeps us on the ground.',cat:'school'},
{w:'hypothesis',p:'n.',c:'假设',s:'Test the hypothesis.',cat:'school'},
{w:'lab',p:'n.',c:'实验室',s:'We work in the lab.',cat:'school'},
{w:'measure',p:'v.',c:'测量',s:'Measure the temperature.',cat:'school'},
{w:'method',p:'n.',c:'方法',s:'What method did you use?',cat:'school'},
{w:'observe',p:'v.',c:'观察',s:'Observe the changes carefully.',cat:'school'},
{w:'physics',p:'n.',c:'物理',s:'Physics is fascinating.',cat:'school'},
{w:'publish',p:'v.',c:'发表',s:'She published a paper.',cat:'school'},
{w:'research',p:'n./v.',c:'研究',s:'Do more research.',cat:'school'},
{w:'result',p:'n.',c:'结果',s:'The results are clear.',cat:'school'},
{w:'science',p:'n.',c:'科学',s:'Science is amazing.',cat:'school'},
{w:'theory',p:'n.',c:'理论',s:'In theory, it should work.',cat:'school'},
{w:'trace',p:'v./n.',c:'追踪',s:'Trace the source of the problem.',cat:'school'},
{w:'volume',p:'n.',c:'体积/音量',s:'Turn up the volume.',cat:'school'},
{w:'actor',p:'n.',c:'演员',s:'He is a famous actor.',cat:'media'},
{w:'art',p:'n.',c:'艺术',s:'I love modern art.',cat:'media'},
{w:'broadcast',p:'v./n.',c:'广播',s:'The news is broadcast daily.',cat:'media'},
{w:'camera',p:'n.',c:'相机',s:'Take a photo with the camera.',cat:'media'},
{w:'channel',p:'n.',c:'频道',s:'Switch to another channel.',cat:'media'},
{w:'character',p:'n.',c:'角色/字符',s:'The main character is brave.',cat:'media'},
{w:'director',p:'n.',c:'导演',s:'The director is brilliant.',cat:'media'},
{w:'documentary',p:'n.',c:'纪录片',s:'I watched a good documentary.',cat:'media'},
{w:'drama',p:'n.',c:'戏剧',s:'She enjoys drama.',cat:'media'},
{w:'edit',p:'v.',c:'编辑',s:'Edit the video carefully.',cat:'media'},
{w:'episode',p:'n.',c:'一集',s:'Watch the next episode.',cat:'media'},
{w:'fiction',p:'n.',c:'小说/虚构',s:'I prefer fiction.',cat:'media'},
{w:'film',p:'n.',c:'电影',s:'Let\'s watch a film.',cat:'media'},
{w:'headline',p:'n.',c:'标题',s:'Read the headlines.',cat:'media'},
{w:'journal',p:'n.',c:'期刊/日记',s:'She writes in her journal daily.',cat:'media'},
{w:'journalist',p:'n.',c:'记者',s:'The journalist asked tough questions.',cat:'media'},
{w:'magazine',p:'n.',c:'杂志',s:'I read this magazine monthly.',cat:'media'},
{w:'novel',p:'n.',c:'小说',s:'This novel is a bestseller.',cat:'media'},
{w:'poet',p:'n.',c:'诗人',s:'He is a famous poet.',cat:'media'},
{w:'publish',p:'v.',c:'出版',s:'The book was published last year.',cat:'media'},
{w:'script',p:'n.',c:'剧本',s:'Write a script for the show.',cat:'media'},
{w:'studio',p:'n.',c:'工作室',s:'We recorded in the studio.',cat:'media'},
{w:'stage',p:'n.',c:'舞台',s:'She performed on stage.',cat:'media'},
{w:'athlete',p:'n.',c:'运动员',s:'He is a professional athlete.',cat:'health'},
{w:'balance',p:'n.',c:'平衡',s:'Practice balance exercises.',cat:'health'},
{w:'breathe',p:'v.',c:'呼吸',s:'Breathe deeply and relax.',cat:'health'},
{w:'calorie',p:'n.',c:'卡路里',s:'Count your calories.',cat:'health'},
{w:'champion',p:'n.',c:'冠军',s:'She is the world champion.',cat:'health'},
{w:'coach',p:'n.',c:'教练',s:'The coach motivated the team.',cat:'health'},
{w:'diet',p:'n.',c:'饮食',s:'A balanced diet is important.',cat:'health'},
{w:'endurance',p:'n.',c:'耐力',s:'Build your endurance slowly.',cat:'health'},
{w:'energy',p:'n.',c:'精力',s:'I need more energy.',cat:'health'},
{w:'exercise',p:'n./v.',c:'锻炼',s:'Exercise every morning.',cat:'health'},
{w:'flexible',p:'adj.',c:'灵活的',s:'Yoga makes you flexible.',cat:'health'},
{w:'injury',p:'n.',c:'伤',s:'He recovered from his injury.',cat:'health'},
{w:'muscle',p:'n.',c:'肌肉',s:'Build muscle with weights.',cat:'health'},
{w:'nutrition',p:'n.',c:'营养',s:'Good nutrition is essential.',cat:'health'},
{w:'protein',p:'n.',c:'蛋白质',s:'Eat more protein.',cat:'health'},
{w:'recover',p:'v.',c:'恢复',s:'It takes time to recover.',cat:'health'},
{w:'stretch',p:'v.',c:'拉伸',s:'Stretch before running.',cat:'health'},
{w:'sweat',p:'v.',c:'流汗',s:'You sweat a lot in summer.',cat:'health'},
{w:'tournament',p:'n.',c:'锦标赛',s:'We won the tournament.',cat:'health'},
{w:'train',p:'v.',c:'训练',s:'Train hard every day.',cat:'health'},
{w:'vitamin',p:'n.',c:'维生素',s:'Take your vitamins daily.',cat:'health'},
{w:'warm',p:'adj.',c:'温暖的',s:'Do warm-up exercises first.',cat:'health'},
{w:'workout',p:'n.',c:'锻炼',s:'That was a great workout.',cat:'health'},
{w:'arrest',p:'v.',c:'逮捕',s:'The police arrested the thief.',cat:'society'},
{w:'court',p:'n.',c:'法庭',s:'The case goes to court.',cat:'society'},
{w:'crime',p:'n.',c:'犯罪',s:'Crime rates are decreasing.',cat:'society'},
{w:'criminal',p:'n.',c:'罪犯',s:'The criminal was caught.',cat:'society'},
{w:'evidence',p:'n.',c:'证据',s:'We need more evidence.',cat:'society'},
{w:'guilty',p:'adj.',c:'有罪的',s:'The jury found him guilty.',cat:'society'},
{w:'innocent',p:'adj.',c:'无辜的',s:'He proved he was innocent.',cat:'society'},
{w:'judge',p:'n./v.',c:'法官/判断',s:'The judge made the decision.',cat:'society'},
{w:'jury',p:'n.',c:'陪审团',s:'The jury reached a verdict.',cat:'society'},
{w:'justice',p:'n.',c:'正义',s:'Justice must be served.',cat:'society'},
{w:'lawyer',p:'n.',c:'律师',s:'Hire a good lawyer.',cat:'society'},
{w:'legal',p:'adj.',c:'合法的',s:'Is this legal?',cat:'society'},
{w:'permit',p:'v./n.',c:'许可',s:'You need a permit.',cat:'society'},
{w:'police',p:'n.',c:'警察',s:'Call the police!',cat:'society'},
{w:'punish',p:'v.',c:'惩罚',s:'He was punished for lying.',cat:'society'},
{w:'right',p:'n.',c:'权利',s:'Everyone has equal rights.',cat:'society'},
{w:'rule',p:'n.',c:'规则',s:'Follow the rules.',cat:'society'},
{w:'sentence',p:'n.',c:'判决/句子',s:'He received a light sentence.',cat:'society'},
{w:'statement',p:'n.',c:'声明',s:'Make a formal statement.',cat:'society'},
{w:'trial',p:'n.',c:'审判',s:'The trial begins tomorrow.',cat:'society'},
{w:'verdict',p:'n.',c:'裁决',s:'The verdict was not guilty.',cat:'society'},
{w:'witness',p:'n./v.',c:'证人/目击',s:'She witnessed the accident.',cat:'society'},
{w:'citizen',p:'n.',c:'公民',s:'Be a responsible citizen.',cat:'society'},
{w:'community',p:'n.',c:'社区',s:'Help your community.',cat:'society'},
{w:'culture',p:'n.',c:'文化',s:'Learn about different cultures.',cat:'society'},
{w:'democracy',p:'n.',c:'民主',s:'We value democracy.',cat:'society'},
{w:'society',p:'n.',c:'社会',s:'Our society is changing.',cat:'society'},
{w:'tradition',p:'n.',c:'传统',s:'Respect old traditions.',cat:'society'},
{w:'values',p:'n.',c:'价值观',s:'Family values matter.',cat:'society'},
{w:'vote',p:'v.',c:'投票',s:'Don\'t forget to vote.',cat:'society'},
{w:'apologize',p:'v.',c:'道歉',s:'I apologize for being late.',cat:'life'},
{w:'appointment',p:'n.',c:'预约',s:'I have a dentist appointment.',cat:'life'},
{w:'arrange',p:'v.',c:'安排',s:'Arrange the meeting for Tuesday.',cat:'life'},
{w:'bake',p:'v.',c:'烤',s:'Bake the cake for 30 minutes.',cat:'life'},
{w:'battery',p:'n.',c:'电池',s:'The battery is dead.',cat:'life'},
{w:'borrow',p:'v.',c:'借',s:'Can I borrow your pen?',cat:'life'},
{w:'brush',p:'v.',c:'刷',s:'Brush your teeth twice a day.',cat:'life'},
{w:'button',p:'n.',c:'按钮',s:'Press the red button.',cat:'life'},
{w:'carpet',p:'n.',c:'地毯',s:'The carpet needs cleaning.',cat:'life'},
{w:'ceiling',p:'n.',c:'天花板',s:'The ceiling is too low.',cat:'life'},
{w:'circuit',p:'n.',c:'电路',s:'The circuit is broken.',cat:'life'},
{w:'closet',p:'n.',c:'壁橱',s:'Hang your coat in the closet.',cat:'life'},
{w:'complain',p:'v.',c:'抱怨',s:'Don\'t complain about everything.',cat:'life'},
{w:'curtain',p:'n.',c:'窗帘',s:'Open the curtains.',cat:'life'},
{w:'decorate',p:'v.',c:'装饰',s:'Decorate the room for the party.',cat:'life'},
{w:'desert',p:'n.',c:'沙漠',s:'The desert is very hot.',cat:'life'},
{w:'drawer',p:'n.',c:'抽屉',s:'Put it in the top drawer.',cat:'life'},
{w:'engine',p:'n.',c:'引擎',s:'The engine makes a strange noise.',cat:'life'},
{w:'entrance',p:'n.',c:'入口',s:'Use the side entrance.',cat:'life'},
{w:'envelope',p:'n.',c:'信封',s:'Put the letter in an envelope.',cat:'life'},
{w:'error',p:'n.',c:'错误',s:'I made an error.',cat:'life'},
{w:'escape',p:'v.',c:'逃跑',s:'They escaped through the window.',cat:'life'},
{w:'fan',p:'n.',c:'风扇/粉丝',s:'Turn on the fan.',cat:'life'},
{w:'fingerprint',p:'n.',c:'指纹',s:'Leave your fingerprint here.',cat:'life'},
{w:'freeze',p:'v.',c:'冻结',s:'Don\'t freeze the vegetables.',cat:'life'},
{w:'garbage',p:'n.',c:'垃圾',s:'Take out the garbage.',cat:'life'},
{w:'grocery',p:'n.',c:'杂货',s:'Buy groceries on the way home.',cat:'life'},
{w:'hammer',p:'n.',c:'锤子',s:'Use a hammer to hang the picture.',cat:'life'},
{w:'helmet',p:'n.',c:'头盔',s:'Wear a helmet when cycling.',cat:'life'},
{w:'ingredient',p:'n.',c:'原料',s:'Mix all ingredients together.',cat:'life'},
{w:'knock',p:'v.',c:'敲',s:'Someone is knocking on the door.',cat:'life'},
{w:'laundry',p:'n.',c:'洗衣',s:'Do the laundry on weekends.',cat:'life'},
{w:'leak',p:'v.',c:'漏',s:'The pipe is leaking.',cat:'life'},
{w:'lock',p:'v./n.',c:'锁',s:'Lock the door when you leave.',cat:'life'},
{w:'mess',p:'n.',c:'混乱',s:'Your room is a mess.',cat:'life'},
{w:'mirror',p:'n.',c:'镜子',s:'Look in the mirror.',cat:'life'},
{w:'nap',p:'n.',c:'小睡',s:'Take a quick nap.',cat:'life'},
{w:'pencil',p:'n.',c:'铅笔',s:'I need a sharp pencil.',cat:'life'},
{w:'pipe',p:'n.',c:'管道',s:'The water pipe is frozen.',cat:'life'},
{w:'plug',p:'n.',c:'插头',s:'Plug in the charger.',cat:'life'},
{w:'pour',p:'v.',c:'倒',s:'Pour some tea for me.',cat:'life'},
{w:'recipe',p:'n.',c:'食谱',s:'Follow this recipe.',cat:'life'},
{w:'refrigerator',p:'n.',c:'冰箱',s:'Put the milk in the refrigerator.',cat:'life'},
{w:'remote',p:'n.',c:'遥控器',s:'Where is the remote?',cat:'life'},
{w:'screw',p:'n.',c:'螺丝',s:'Tighten the screw.',cat:'life'},
{w:'shelf',p:'n.',c:'架子',s:'Put books on the shelf.',cat:'life'},
{w:'shovel',p:'n.',c:'铲子',s:'Use a shovel to clear the snow.',cat:'life'},
{w:'sofa',p:'n.',c:'沙发',s:'Sit on the sofa.',cat:'life'},
{w:'stove',p:'n.',c:'炉子',s:'The soup is on the stove.',cat:'life'},
{w:'switch',p:'n./v.',c:'开关',s:'Turn off the switch.',cat:'life'},
{w:'tap',p:'n.',c:'水龙头',s:'Turn off the tap.',cat:'life'},
{w:'thermometer',p:'n.',c:'温度计',s:'Check the thermometer.',cat:'life'},
{w:'torch',p:'n.',c:'手电筒',s:'Use a torch in the dark.',cat:'life'},
{w:'trash',p:'n.',c:'垃圾',s:'Throw it in the trash.',cat:'life'},
{w:'vacuum',p:'n./v.',c:'吸尘器',s:'Vacuum the carpet.',cat:'life'},
{w:'wallet',p:'n.',c:'钱包',s:'I lost my wallet.',cat:'life'},
{w:'wax',p:'n.',c:'蜡',s:'The candle wax melted.',cat:'life'},
{w:'wrench',p:'n.',c:'扳手',s:'Use a wrench to fix the pipe.',cat:'life'},
];